sourcetext = new Array("In seiner Wohnung ass Thomas Weisswurst und trank Most dazu",
"Die Wanderer beobachteten, wie der Wolf durch den Wald lief",
"Willi entdeckte schwere, schwarze Gewitterwolken am Himmel",
"Werner Oser kaufte Wolfgang den rosafarbenen Wohnwagen ab",
"Internationale Kontakte sind heutzutage weltweit wichtig",
"Die Wanderer aus Oslo suchten den Wegweiser nach Wohlen",
"Die Wohnung im Obergeschoss wird an Oskar Kogens vermietet",
"Warum wandert Swen wohl immer nur im Wangener Wald herum",
"Der wunderbare Weihnachtsbraten wurde wahrhaftig gegessen",
"Wochenlang strich er Wallwurzsalbe auf die Schmerzstelle",
"Das umfangreiche Warenangebot war originell und vorteilhaft",
"Wollt ihr die monatelange Weltreise zu zweit wirklich wagen",
"Oskar telefoniert ununterbrochen wegen dieser Wollstoffe",
"Das Novemberwetter an der Ostsee war oft bewölkt und windig",
"Der wachsame Wolfshund Rico verfolgte die Situation genau",
"Am kommenden Mittwoch fahren Walter und Wilma nach Wollerau",
"Sie konnten am Schwarzsee weder schwimmen noch schnorcheln",
"Wohlwollend las Doktor Mortimer Theos Bewerbungsschreiben",
"Die Kollektion des Modedesigners wurde ein grosser Erfolg",
"Am Bahnhof Wil warteten viele Menschen im warmen Wartesaal",
"Auch der weltgewandte Wirtschaftsjournalist wurde bestohlen",
"Wortlos schob Wolfgang das Motorboot ins Wasser der Ostsee",
"Der kleine Wanderzirkus Robinson wechselt oft den Standort",
"Diese Baumwolle wird im Osten zu rotem Stoff verarbeitet",
"Television und Kino feiern weltweit hervorragende Erfolge",
"Der bewusstlose Wolf wurde im Zoo als Notfall eingeliefert",
"Zahnarzt Zurfluh zog Zita im Oberkiefer einen Stockzahn",
"Zivile Zollbeamte zerrten den Zeugen in die Zollzentrale",
"Wolfgang Borcherts Gesamtwerk erschien im Rowohlt Verlag",
"Omnia vincit amor und cogito, ergo sum sind bekannte Zitate");