sourcetext = new Array("Der peruanische Polizist trug seinen Pudel Lumpi zum Park.",
"Ohne Passwort kann Peter das Computerprogramm nicht öffnen.",
"Gion ass Spaghetti vongole in der piemontesischen Pizzeria.",
"Papagei Poldi plappert am Morgen ununterbrochen Quatsch.",
"Die Exkaiserin lebt in einem Prunkpalast in St. Petersburg.",
"Die prachtvollen Pfirsiche wurden mit Pestiziden gespritzt.",
"Als Vorspeise liebt Pia verquirlten Rahmquark mit Quitten.",
"Peddigrohr wird gerne zum Flechten von Korbwaren benutzt.",
"Eine Politesse schrieb Opa die Quittung seiner Parkbusse.",
"Pirmin verzollte in Paris einen wertvollen Perserteppich.",
"Papst Pius predigte am Ostersonntag im Petersdom in Rom.",
"Monika holte eine Puderquaste in der Drogerie in Landquart.",
"Die Philharmoniker proben oft nur mit Pauken und Trompeten.",
"Der polnische Pingpongspieler gewann in Peking einen Pokal.",
"Die Produktion der Quarzlampen in Oxford wurde gesteigert.",
"Quebec ist eine Provinz und ebenso eine Stadt in Kanada.",
"Unter einem Quacksalber versteht man oft einen Kurpfuscher.",
"Die Primaballerina tanzt die Quadrille ohne Orchestermusik.",
"Paul ass grosse Portionen Popcorn und trank Grapefruitsaft.",
"Der Skispringer landet prima auf der Piste im Pulverschnee.",
"Pronto, ruft der Prokurist ins Mikrofon seines Telefons.",
"Plötzlich stand der Postbote mit dem Paket vor dem Pfarrer.",
"Bei TV DRS sind die Zuschauerquoten im neuen Quartal höher.",
"Die Professorin erkrankte im April plötzlich an Grippe.",
"Polo Hofer textet und produziert die Mundartsongs in Bern.",
"Die Bremsen quietschten, als der Pilot die Piper stoppte.",
"Im September erntete Jacques Peperoni, Äpfel und Quitten.",
"Unser Perserkater Hopla spaziert auf der Piazza San Pavese.",
"Pfirsiche und Aprikosen zerquetschten auf dem Transport.");