sourcetext = new Array("Pünktchen und Anton wurde von Erich Kästner geschrieben.",
"Hängemäppchen sind äusserst praktisch für ihre Benützer.",
"Jürgen ist häufig Käufer von Antiquitäten und Raritäten.",
"Prächtige Sträusse werden an Ständen günstig angeboten.",
"Füchse leben in Wäldern und neuerdings auch in Städten.",
"Sämi schätzt ein zünftiges Frühstück mit Müesli und Käse.",
"Käserösti und Älplermakronen sind bäuerliche Spezialitäten.",
"Das fünfjährige Büblein hüpfte übermütig über die Wiese.",
"Es finden täglich drei günstige Flüge nach Lübeck statt.",
"Ärzte empfehlen, die Haut vor Umwelteinflüssen zu schützen.",
"Bärlauch und Sauerampfer sind beliebte Frühlingskräuter.",
"Die Ehrengäste schüttelten Hände und erhielten Sträusse.",
"Am Fraumünsterplatz wird süsses Blätterteiggebäck serviert.",
"Die Zürcher Assistenzärzte fordern kürzere Arbeitseinsätze.",
"Übermütig begrüsste Käthchen die lächelnde Kindergärtnerin.",
"Der verärgerte Ringkämpfer entwickelte wahre Bärenkräfte.",
"Andis nächstes Fest wird unzählige Überraschungen bieten.",
"In Ralfs Antiquariat werden üblicherweise Bücher angeboten.",
"Fredi Bärs Aquarelle bürgen für aussergewöhnliche Qualität.",
"Das Präparat aus den chinesischen Wurzeln ist ungefährlich.",
"Das prächtige Gemälde von Vincent van Gogh hängt im Louvre.",
"Tatsächlich fand Detektiv Lässer viele verdächtige Spuren.",
"Im Allgäu krähen die Hähne und klappern die Störche laut.",
"Der Nachtwächter Bürgi überprüfte den nächtlichen Überfall.",
"Der Präsident des Vereins wirkte jähzornig und ungemütlich.",
"Er hat kein Gespür für die Bedürfnisse der jüngeren Bürger.",
"Verstärkte Motoren versprechen künftig präzisere Qualität.",
"Ivo Bär liebt Würste und würzigen Kümmelkäse zum Frühstück.",
"Müller feiert überglücklich sein längst fälliges Jubiläum.",
"Harte Getränke sind nicht nur für jüngere Leute schädlich.");