sourcetext = new Array("Das hypermoderne Haus mit den Glyzinien steht auf Zypern.",
"Die dynamische Elly bereist mit dem Hymer den Bryce Canyon",
"Tilly Meyer aus Bayern ist eine hyperaktive Volleyballerin",
"Der Yogalehrer hat seine physischen Schwächen überwunden.",
"Mysteriöse Spuren haben den flüchtigen Täter überführt.",
"Mächtige Zypressen säumten das Strässchen zum Jachtclub.",
"Die x-fache Weltmeisterin übersprang die Hürden präzise.",
"Yves und Yvonne besuchten Yverdon und das Greyerzerland.",
"Yesterday und Yellow Submarine sind Songs von den Beatles.",
"Unzählige Touristen besuchen den Yellowstone-Nationalpark.",
"Die Pyramiden sind Grabmäler der altägyptischen Könige.",
"Gregory hat sein Psychologie-Studium in New York beendet.",
"Playboy Henry trinkt an der Cocktailparty einen Whisky.",
"Die Firma Gymtech verkauft hypermoderne Gymnastikgeräte.",
"Maximilian ist ein analytischer und systematischer Denker.",
"Soraya tanzt den Calypso äusserst rhythmisch und dynamisch",
"Der Hypnotiseur hat gelbe Chrysanthemen in Sydney gekauft.",
"Hans Guyer hat sein Kanal-System als Prototyp angeboten.",
"Harry Meyer sang eine Hymne an der Silvesterparty auf Sylt",
"Polyamid-, Nylon- und Polyesterstoffe sind pflegeleicht.",
"Im Film Rocky verkörperte Sylvester Stallone einen Boxer.",
"Unter einem Pseudonym schrieb der Schriftsteller die Lyrik",
"Lydia Gygax verfolgte die Eishockey-Meisterschaft in Vevey",
"Dany Wyler-Meyer hat einen roten Chrysler Voyager gekauft.",
"Der Name des Yorkshireterriers sollte mit Ypsilon beginnen",
"Happy New Year wünschte Bryan seinem Freund Cyrill Taylor.",
"In Aix-en-Provence trafen sich die Harley-Davidson-Fahrer.",
"Voll trendy ist Vitamin-C-haltiges Functional-Food-Getränk",
"Das Ins-Blaue-Fahren liebten unsere Grossmütter und -väter",
"Die Mund-zu-Mund-Beatmung ist im Mai-Juni-Heft Hauptthema.");