sourcetext=new Array("sandra isst selleriesalat und randensalat sie trinkt kaffee",
"ursula reisst an der leine dieser stein ist rund und dunkel",
"der unfall sei ernst die fassade ist neu nun ruft anna an",
"das kind erkennt nina nie ulla ist eine alte treue kraft",
"seidenkleider sind teuer andi renkt ein erna streitet laut",
"fast eine stunde dauert der streit an ursula niest laut",
"die ratte starrt in die luft das kleinkind sinkt stark ein",
"das kleefeld ist nass er findet das rad tina rennt alleine",
"elli sei allein unter der tanne sara denkt lauter unsinn",
"der alte esel rennt runter trenne die streitenden leute",
"teddi ist in drei stunden in stansstad in der reitstunde",
"karl und ella finden diese steilen kalkfelsen interessant",
"frau keller reist ins tessin und in den jura in die ferien",
"in illnau fördert andi steiner kinder in den kleinklassen",
"seine talente sind klasse urs erkennt diesen klaren stern",
"der kreis ist rund das restaurant sternen ist leider teuer",
"sie rufen den entlaufenen rindern renate ist ueli treu",
"die lila teller und tassen sind neu dieser saft ist sauer",
"die erkrankte tante ria reiste in aller eile aus indien aus",
"der ölkanister ist leider leer lass uns nun alleine trinken",
"draussen ist es dunkel und kalt sie trinkt nur kalten tee",
"lila natels sind der neue trend sandra ist still und leise",
"erna erfindet neue lieder karla kauft seine anteile auf",
"er ist unten auf der terrasse und isst diese feinen nudeln",
"der starke fluss reisst den kleinen stein ins tal runter",
"dani kauft allerlei neues ein rudi kieser denkt nie laut",
"das tennisturnier findet in einer stunde in illnau statt",
"nina junker tröstet kurt sina kuster teilt die karten aus",
"dies ist unsere sternstunde tina und urs kauften feinen tee",
"fasse die neun sisalseile fest an tina findet tennis stark");



