sourcetext = new Array("dreissig junge hunde irrten die strasse hinauf und hinunter",
"dieses dunkle leinenkleid ist uns an der feier aufgefallen",
"die jaguare sind in freiheit ninas flug landet in stuttgart",
"der erstklassige intendant des theaters ist aufgestellt",
"der graue esel ist stur der lehrer ist ruhig und gefasst",
"gerda sandte einen strauss fresien diese serie ist klasse",
"edith ist sehr gesund dies ist ein erstklassiges dessert",
"rudi artikuliert klar der flugtestfahrer ist ausgelastet",
"hastig sagte ursi lisa ade der förster kaufte öl aus afrika",
"isa sieht diese tierart in der natur tina ist jung und klug",
"die junge frau gellert und kurt kuster fahren rudis fahrrad",
"anne gut reist nie ins tessin andreas hatte einen streit",
"der atlantikflug ist neuerdings nur dienstags und freitags",
"hansjörg feller leitet die gut rentierende haushaltfiliale",
"die höhle der kröte ist dunkel gerda lief den hang hinauf",
"der hund ist seit gestern entlaust und frisst sein futter",
"urs eugster geht in neun sekunden in stuttgart an den start",
"igel sind kleine tiere gertruds gute ideen sind leider rar",
"er hat indiskrete fragen an den jungen ingenieur gestellt",
"hans hasler aus glarus ist ein erstklassiger jagdaufseher",
"elf tage lang ist in den gassen festen und gesang angesagt",
"es sind kundinnen die nur allerfeinste seidenkleider kaufen",
"freudig erstand fredi heusser diesen teuren antiken stuhl",
"der tierhalter keller sagt die jungtiere seien angriffig",
"sandra und ihre freunde geniessen das reiten in der natur",
"dieser interessante stern strahlt hell in der dunkelheit",
"die skifahrer trinken heissen kaffee anstatt kalten tee",
"unser giraffenkind luana ist heute genau dreissig tage alt",
"der kleine uhu ugandu frisst alles futter aus der hand",
"der elefant salaika liegt ruhig draussen unter der tanne");



