sourcetext = new Array("Sie verbringt die Zeit bis zum Mittagessen im Firmenbeizli",
"Rufen Sie bei der Firma in Bern an und bestellen Sie Blei",
"Die Braut hat siebenhundertzehn Briefe und Zettel gelesen",
"Im Herbst fahren Mia und Ria mit der Eisenbahn ins Burgund",
"Danis beliebter Bruder benutzt zur Zeit Zitas Bahnbillett",
"Bettina hat den Briefen vier Dutzend Briefmarken beigelegt",
"Er baut zur Zeit eine zentrale Brennmaterialfabrik in Basel",
"Hinter diesem Birnbaum bellte der böse blinde Hund Bella",
"Der brave Lehrling setzte dutzende der Briefe selber auf",
"Beni Zuber ist ein bekannter Kundenberater im Bezirk Bern",
"Sie bestaunten ihre bunt bemalten Gartenmöbel auf der Zinne",
"Der breitbeinige Begleiter aus Brasilien bezahlte das Bier",
"Lea sass am viel befahrenen Ufer des Sees und ass Haferbrei",
"Bei Barzahlung der blauen Badeartikel gibt es Zusatzrabatt",
"Sabine und Sebastian nahmen eine bunte Vitamintablette ein",
"Seine Begnadigung fand die Zustimmung der Landbevölkerung",
"Er besitzt zehn Zahlungsbefehle des Zahnarztes aus Zizers",
"Der Tannenbaum verbrannte innerhalb einer Viertelstunde",
"Seine umfassende Briefmarkensammlung ist billig zu haben",
"In ihren Herbstferien nahmen Gabi und Zita Gesangsstunden",
"Seine bezaubernde Rede erntete Zustimmung und viel Beifall",
"Isabella Burkhards Badezimmer ist immer blitzblank sauber",
"Er glaubt an eine baldige Besserung der Bazillenerkrankung",
"Der blinde Franz bestellte Bier und Leberknödel mit Erbsen",
"Bruna besitzt ein billiges Einzelzimmer im Zentrum Biels",
"Die Bude ist bestens möbliert und hat zudem Zentralheizung",
"Er bringt das Bettzeug mit und benutzt das neue Zusatzbett",
"Heute fahren Berner und Basler ins Zentrum der Stadt Luzern",
"Herr Braun feierte den siebzigsten Geburtstag im Zillertal",
"Gelbe Ringelblumen und blaue Mauritius beleben graue Mauern");