sourcetext = new Array("Ich beeile mich, damit ich rechtzeitig in Sirnach eintreffe",
"Erich reiste nach Hause, um seine Arbeit schnell zu beenden",
"Die Nachricht, die Beni uns sandte, erreichte uns zur Zeit",
"Ich vergass, meinen Briefen alle vier Rechnungen beizulegen",
"Der Freund, an den ich ihn erinnerte, fuhr zuerst nach Biel",
"Das Buch, das Chiara mir geschickt hatte, schenkte ich Vera",
"Ich habe im Juli meine Abschlussarbeit endlich abgegeben",
"Diese deutsche Zeitschrift gilt auf ihrem Gebiet als teuer",
"Christina, Claudia und Evi besuchen den trendigen Surfkurs",
"Achmed hat seine Zigaretten mit Streichhölzern verbrannt",
"Die Metzgerei Schiller in Sitten verkauft das beste Fleisch",
"Hans Meier benutzt Raffaels Atelier zum Malen seiner Bilder",
"Dani hat Sabrinas Tisch geschliffen und schön verarbeitet",
"Benjamin schreibt Reiseberichte, aber auch Tiergeschichten",
"Regula Zeller, schreibt man, sei auch eine begnadete Köchin",
"Das bekannte Museum ist umgebaut und öffnet neu im Dezember",
"Das schöne, neue Heim steht am steilen Hang unterhalb Buchs",
"Der Chirurg bezahlte das Buch mit einem gekreuzten Scheck",
"Mit diesem Medikament stehen die Chancen einer Heilung gut",
"Der Nichtraucher schlich lachend um das einsame Zelt herum",
"Das Kleinkind trinkt gut und hat etliches Neues dazugelernt",
"Zigarettenrauchen ist eine Sucht, die mehr und mehr zunimmt",
"Christian Höchner ersetzt seine teure, lederne Brieftasche",
"Er charakterisiert seine Ideen charmant und beeindruckend",
"Der Berichterstatter mag den gebackenen Fisch nicht essen",
"Der Schiedsrichter des Fussballclubs Grenchen heisst Jack",
"Der Dichter Friedrich Schiller schrieb Gedichte und Dramen",
"Seit dem Bienenstich leidet der Dachs unter einer Allergie",
"An unserer Schule lernt man Rechnen, Schreiben und Zeichnen",
"Brecht, Frisch und Bichsel sind Dichter und Schriftsteller");