sourcetext = new Array("Der Mainzer Johannes Gutenberg erfand die Buchdruckerkunst.",
"Random Access Memory heisst auf Deutsch Arbeitsspeicher.",
"Die Lebensader Ägyptens ist sein einziger Fluss, der Nil.",
"Icons heissen die Bildchen auf dem Bildschirm der Computer.",
"Gin-Rummy ist ein Kartenspiel für zwei bis vier Personen.",
"Neue Strategien tragen dazu bei, diesen Konflikt zu lösen.",
"Max Beyeler züchtet Königsparadiesvögel und Zwergpapageien.",
"Er kauft Papier- und Kuvertformate der A-, B- und C-Reihe.",
"Armin Färber bereitet sich auf das Anstellungsgespräch vor.",
"Sie liebt klassische Musik ebenso sehr wie Rock und Pop.",
"Das Textverarbeitungsprogramm Word hat zahlreiche Stärken.",
"Punkt, Punkt, Komma, Strich und fertig ist das Angesicht.",
"Texte in Grossbuchstaben beeinträchtigen die Lesbarkeit.",
"Der Crap Sogn Gion bei Laax ist ein Muss für Snowboarder.",
"Dies ist doch keine knochentrockene Bild- und Textanalyse.",
"Die Grotte de Combarelles in der Dordogne ist geöffnet.",
"Die Hypothekarzinsen kommen auf breiter Front ins Rutschen.",
"Im Grossmarkt wird der Merlot del Veneto günstig angeboten.",
"Beachte die neuen Öffnungszeiten von Montag bis Freitag.",
"Am Dienstag tauschte er den Cadillac gegen einen Chevrolet.",
"Angeboten werden verschiedene Kleider zu günstigen Preisen.",
"Der Grossvater war Berufsmusiker, Organist und Musiklehrer.",
"Problemlösungen sind Über die Grenzen hinaus zu suchen.",
"Der ZÜrcher Otto Äppli spielt nicht nur Blues, er lebt ihn.",
"Der kurdische Literaturwissenschaftler lebt in der Türkei.",
"Seine Mischtechnikbilder erzählen von Auseinandersetzungen.",
"Der Adler zählt zu den beeindruckendsten Tieren der Alpen.",
"Der Comicsammler tauscht Liebesromane gegen Batmanhefte.",
"Überzeugter Nichtraucher sucht Dreizimmer-Wohnung in Genf.",
"Lieber ein Ende mit Schrecken als ein Schrecken ohne Ende.");