sourcetext = new Array("Trixi und Traxi sind die exakten Namen von Xavers Katzen.",
"Im extravaganten Hotel Excalibur trank Alexia alles ex.",
"Mit dem Excel kann man exakt rechnen, nicht aber texten.",
"Der extrovertierte, exzentrische Exilkubaner liebt Lexia.",
"Er zerteilt die Kalbshaxe mit einer extrem scharfen Axt.",
"Xenia blies das Saxofon im Luxushotel Excelsior in Bex.",
"Die Exmatrikulation von der Uni Exeter macht ihn traurig.",
"Max hat Boxershorts in der Grösse XXS in Luxemburg gekauft.",
"Diese verflixte Hexe mixt ihre Mixturen mit einem Mixer.",
"Axel Mettler kaufte den texanischen Trax sofort via Fax.",
"Verbissen boxte Boxer Willi in der Bronx um seine Existenz.",
"Die Gitarrenschule von Maximilian rentierte verflixt gut.",
"Im Fextal geniessen Trix und Max eine scharfe Oxtailsauce.",
"Die Bustaxen werden in Luzern bald wieder extrem erhöht.",
"Der Foxtrott ist der Lieblingstanz dieser zwei Mexikaner.",
"Die Faxnummer der Textilfirma Xerotex ist extrem einfach.",
"Zum Texten benötigt Xaver oft ein französisches Lexikon.",
"Diese Examenstexte taxierte Roger als hochgradig schwierig.",
"Die Mixtur wird vom Toxikologischen Institut untersucht.",
"Der Boxerhund Rex ist ein exzellenter Begleiter und Freund.",
"Die Textverarbeitung ist heute in allen Betrieben existent.",
"Fechten verlangt unter anderem einen extrem guten Reflex.",
"Einen Sextanten verwendet man als Winkelmessinstrument.",
"Er kauft die extravaganten Boxershorts nur im Luxusladen.",
"Das exklusive Essen in exotischer Umgebung gefiel Alexia.",
"Wenn man Examenstexte gut kennt, sind sie keine Hexerei.",
"Seine Exzellenz, Exkönig Xeno, zog ins Exil nach Montreux.",
"Die Firma Flex bot dem Exskifahrer den Exklusivvertrag an.",
"In meinem Traum tanzten Hexen mit Nixen um König Xerxes.",
"Alexander Bexter arbeitet als Taxifahrer in Alexandria.");