sourcetext = new Array("susis lila kleid aus seide sei edel öle ursulas rad leise",
"ullas idee fiel diara auf dieser ölkessel lief leider aus",
"aller friede sei auf dieser erde erlöse alle diese elf esel",
"rufe du erika aus der klasse klara fiel auf alle feldsessel",
"aus freude riss ulla die lilie aus der erde rudi darf das",
"die eisfassade der reederei fiel sira auf löse diese öse",
"lillis auflauf freue frau klaas aus aarau fasse diese keule",
"freddis ausruf fiel leider leise aus dies sei lisas seife",
"aus freude lud lukas alle diese seile auf das kajak auf",
"das ruder des kajaks sei urs das lied erfreue die flösser",
"die filiale der eisdiele sei klasse der fluss fliesse leise",
"ursis fideles lied erfreue alle das dia der klasse sei edi",
"dieser safe sei der idealfall dieses fass dieselöl sei urs",
"der kaffee lief auf das fell aus der riese sei aus adelaide",
"ulrike ass lisas reisauflauf diese adriareise erfreue urs",
"der eierlikör sei aus sursee alfred ass das saure eis auf",
"rufe du rudi keller aus israel aus der ruderkurs sei ideal",
"des kakadus federkleid sei lila susis ausdauer sei klasse",
"der eilkurier las diese skurrile idee luise sei leider faul",
"diese rasierseife fiel auf ulrikes kleider ella sei frei",
"das feuer der ölfelder fiel ursula auf eduard las alles",
"der ausreisser aus aarau sei da lilis reisekasse sei leer",
"der fidele ruderer ass alle diese eier auf ulrike sass da",
"auf der safari fiel alida das kudurudel auf edi reue das öl",
"das karussell aus israel sei leise edis ausrede sei klasse",
"alfreds dauerlauf fiel laura deller aus sursee leider auf",
"daria sass auf der kasse der kaffee lief auf die faule laus",
"rösli las die öse auf auf der reise fiel urs auf sei leise",
"der kaffeekessel sei leer ursula las alle kaffeelöffel auf",
"dalida kaufe das dieselöl leider ass die klasse alle kekse");


