sourcetext = new Array("magda malte mandarinenten am marmarameer mama mag marmelade",
"im juli verreist vreni vetter ans filmfestival in hilversum",
"der terminkalender des magiers aus mittelamerika ist mager",
"die vielfalt der vasen im völkermuseum gefiel verena sehr",
"in amerika misst man strassen anstatt in meter in meilen",
"vladimir verhökerte sein veraltetes und verstimmtes klavier",
"minutenlang massierte er alle meine muskeln mit mistelöl",
"der musikkritiker verlegte den vertrag des musikverlegers",
"dem malermeister gefallen mehrere dieser metallmuster sehr",
"die vermittler verteilten die gelder an die vereinskassen",
"der magere sheriff ritt auf dem maulesel im maisfeld umher",
"das strafverfahren gegen den stellvertreter ist eingeleitet",
"die amerikaner erkunden den mars mittels riesiger raketen",
"veras vetter valentin stammt aus den vereinigten staaten",
"maria und mara treffen einander mehrmals im jahr in malage",
"der detektiv verhaftet den vikar im vareser altstadtviertel",
"die miete meines neuen heims in mannheim ist minimal klein",
"der vermittler vermietete meinem vater eine villa in vals",
"aufmunternd jagte magier marius das massige kamel umher",
"mutig verliess das vier jahre alte elefantenkind das revier",
"hans legte den marderköder mehrmals in mutters kammer aus",
"mehrere umleitungen sind in interlaken seit langem angesagt",
"das maismehl ist fein gemahlen mama kauft salami in meran",
"vrenis verteidiger verlangte ein verhör des angeklagten",
"matthias ist im mai als musiker in die armee eingetreten",
"vermehrt verlangen die kunden einen ausverkauf der klaviere",
"der massenmörder aus mammern tötete den mann mit dem messer",
"stefan malte jeden millimeter seines elternhauses neu an",
"musstest du meiner mutter immer alles melden und mitteilen",
"am vierten juni verkaufte der vertreter viele arvengestelle");