sourcetext = new Array("Dieser attraktive Vietnamese verfehlte die Kurve in Venedig",
"Er kaufte Mitte Mai Damast am Meter Alma meidet Margarine",
"Valerie heiratet den smarten Verkaufsleiter Völlmer im Juni",
"Mehrmals leitete er den Malmöflug um Tim ist meistens mutig",
"David fuhr die Fremden aus Venedig in die Mitte der Stadt",
"Die Mehrheit meidet die maulende und jammernde Marianne",
"Nun ist die vergiftete Amsel auf der alten Tanne verstummt",
"Der Regisseur dreht mehrmals im Jahr einen grausamen Film",
"Eveline sang den Vers mit vielen andern im Viervierteltakt",
"Manu realisiert langsam die Mehrheit ihrer Mathematikfehler",
"Die Eröffnung des Vereinatunnels freute den Radfahrerverein",
"Auf der Safari sah der Filmer ausgemergelte Kamele und Emus",
"Der Revierförster hatte die Vögel im Visier des Fernglases",
"Der Hund isst Mengen dieser mehligen mastigen Maiskörner",
"Mit Verdruss ass Anatevka viel Kaviar und trank Veltliner",
"Die Mehrheit reist im August ans Mittelmeer in die Ferien",
"Dieses Jahr findet Verdis Musikfestival in der Arena statt",
"Mara Möller aus Madagaskar mag Misteln Murmeln und Mandeln",
"Der Festivalveranstalter in Vella versandte die Einladungen",
"Marius feierte das Millennium mit Mirtha und DJ Midi Miller",
"Es ist ein Jammer dass Milvas Ideen völlig veraltet sind",
"Melitta Maas misst die Kammer millimetergenau und minutiös",
"Dieses Vlies ist eine Neuheit und erst seit Mai im Verkauf",
"Der muntere Senn mistet den Stall auf der Alm mehrmals aus",
"Die verdatterte Amsel erkannte die Feldmaus aus der Ferne",
"Mutig jagt dieser junge Mann den starken muskulösen Tiger",
"Er rief seine vier Kinder an und verreiste dann ins Veltlin",
"Margrit Messmer studiert Ameisennester und Termitenstaaten",
"Die Fahnen am Amateurfilmfestival Genf sind meist gehievt",
"Mark Miller aus Manhattan ist Mitglied dieser Vereinigung");
